version: '3'
services:
  rabbitmq:
    hostname: 'rabbit1'
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"
      - "5671:5671"
    volumes:
      - "./data:/var/lib/rabbitmq/mnesia/"
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge